# ─────────────────────────────────────────
# API — ASP.NET Core 10
# ─────────────────────────────────────────
version: '3.9'

services:
  admin-tickets:
    container_name: admin-tickets-ismael

    build:
      context: .
      dockerfile: Dockerfile

    image: admin-tickets-ismael:latest

    ports:
      - "5204:8080"

    restart: unless-stopped


